<?php

namespace Tests\Feature;

use App\Admin;
use App\User;
use Faker\Factory;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class LandingTest extends TestCase
{
    use RefreshDatabase;

    /**
     *
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    /**
     * @test - Returns 200 if landing page working
     * */
    public function landing_page_test()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }

    /**
     * @test - Redirecting not logged in users to login page.
     */
    public function not_logged_in_users_redirect_to_login_page()
    {
        $response = $this->get('/home');
        $response->assertRedirect('/admin/login');
    }

    /**
     * @test - allow logged in users to view home page.
     */
    public function allow_logged_in_admin_to_view_home_page()
    {
        $this->actingAs(\factory(Admin::class)->create());
        $response = $this->get('/home');
        $response->assertOk();
    }
}
