<?php

namespace Tests\Unit;

use App\Container;
use App\Http\Controllers\MonitoringValidationController;
use App\ReeferMonitoring;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class MonitoringValidationTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->container = new Container();
        $this->container->container_number = 'SZLU9553015';
        $this->container->loading_discharging = 'L';
        $this->container->yard_location = 'K30';
        $this->container->ts_local = 'EXP';
        $this->container->temperature_unit = 'C';
        $this->container->set_temp = '20';
        $this->container->plug_on_date = '2019-09-01';
        $this->container->plug_on_time = '02:26:00';
        $this->container->plug_on_temp = '22';
        $this->container->ex_on_career_vessel = '54';
        $this->container->ex_on_career_voyage = '61';
        $this->container->plugging_category = 	'monitoring';
        $this->container->save();

        $this->monitoring = new ReeferMonitoring();
        $this->monitoring->container_id = $this->container->id;
        $this->monitoring->date = $this->container->plug_on_date;
        $this->monitoring->schedule_4 = '22.00';
        $this->monitoring->save();

        $this->request = new \stdClass();
        $this->request->schedule_4 = '22.00';
        $this->request->schedule_8 = null;
        $this->request->schedule_12 = null;
        $this->request->schedule_16 = null;
        $this->request->schedule_20 = null;
        $this->request->schedule_24 = null;
        $this->request->plug_off_date = '2019-09-01';
        $this->request->plug_off_time = '4:30:00';
        $this->request->plug_off_temp = '20';


    }

    /**
     * Plug off same day as plug on and has monitoring on that day
     * @test
     * @return void
     */
    public function plug_off_same_date_as_plug_on_and_has_monitoring_valid_fill()
    {
        $this->withoutExceptionHandling();

        $this->monitoring_validation = new MonitoringValidationController($this->container->id,$this->request);

        $this->assertTrue($this->monitoring_validation->isValidFill());
    }

}
