<?php

namespace Tests\Unit;

use App\Vessel;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class VesselTest extends TestCase
{
    use DatabaseMigrations;
    public $vessel;
    /**
     *
     */
    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->vessel = factory(Vessel::class)->make();

    }

    /**
     * A basic unit test example.
     * @test
     * @return void
     */
    public function check_vessel_name_and_code()
    {
        $this->assertNotEmpty($this->vessel->name);
        $this->assertNotEmpty($this->vessel->code);
    }
}
